//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_KeyPadImages 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    KeyPadImages *pCmd;
  } CltChCmd_KeyPadImages;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct SvrChCmd_HDINT 
  {
    CMDMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_HDINT;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

